AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DemoDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: demo1-app6-tbl
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"

  DemoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: demo1-app6-tbl
      CodeUri: demo-app/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        Visits:
          Type: Api
          Properties:
            Path: /visit
            Method: post 

  DemoWebsite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketName: awsawesome-fransisco-cloud-resume

  BucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
     PolicyDocument:
       Id: DemoPolicy
       Version: 2012-10-17
       Statement:
         - Sid: PublicReadForGetBucketObjects
           Effect: Allow
           Principal: "*"
           Action: "s3:GetObject"
           Resource: !Join
             - ""
             - - "arn:aws:s3:::"
               - !Ref DemoWebsite
               - /*
     Bucket: !Ref DemoWebsite

  DemoDistribution:
   Type: "AWS::CloudFront::Distribution"
   Properties:
     DistributionConfig:
       ViewerCertificate:
         AcmCertificateArn: !Ref DemoCertificate
         SslSupportMethod: sni-only
       Aliases:
         - resume.nphmultan.com
       DefaultCacheBehavior:
         ViewerProtocolPolicy: redirect-to-https
         TargetOriginId: awsawesome-fransisco-cloud-resume.s3-website-us-east-1.amazonaws.com
         DefaultTTL: 0
         MinTTL: 0
         MaxTTL: 0
         ForwardedValues:
           QueryString: false
       Origins:
         - DomainName: awsawesome-fransisco-cloud-resume.s3-website-us-east-1.amazonaws.com
           Id: awsawesome-fransisco-cloud-resume.s3-website-us-east-1.amazonaws.com
           CustomOriginConfig:
             OriginProtocolPolicy: http-only
       Enabled: "true"
       DefaultRootObject: index.html

  DemoRoute53Record:
   Type: "AWS::Route53::RecordSetGroup"
   Properties:
     HostedZoneId: Z06559322AO5UYWN1RZ75
     RecordSets:
       - Name: resume.nphmultan.com
         Type: A
         AliasTarget:
           HostedZoneId: Z2FDTNDATAQYW2
           DNSName: !GetAtt DemoDistribution.DomainName

  DemoCertificate:
     Type: AWS::CertificateManager::Certificate
     Properties:
       DomainName: resume.nphmultan.com
       ValidationMethod: DNS

Outputs:
  DemoLambdaFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for DemoLambdaFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  DemoLambdaFunction:
    Description: "DemoLambdaFunction ARN"
    Value: !GetAtt DemoLambdaFunction.Arn
  DemoLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for DemoLambdaFunction"
    Value: !GetAtt DemoLambdaFunction.Arn
